from datetime import datetime, timezone
import re
from typing import Literal, Optional
from pydantic import BaseModel, ConfigDict, Field, field_validator


# Reject API keys, tokens, and private keys anywhere in identity fields
SECRET_PATTERNS = [
    re.compile(r"(Bearer\s+[a-zA-Z0-9._-]+|sk-[a-zA-Z0-9_-]{8,}|ghp_[a-zA-Z0-9]{10,}|eyJh[a-zA-Z0-9_-]{20,}|-----BEGIN\s+[A-Z\s]+PRIVATE\s+KEY-----)", re.IGNORECASE),
    re.compile(r"(password\s*=\s*\S+|secret\s*=\s*\S+|api_key\s*=\s*\S+|token\s*=\s*\S+)", re.IGNORECASE),
]


class AgentIdentity(BaseModel):
    """
    Structured, immutable identity representing an autonomous or semi-autonomous agent.
    Supplied exclusively by trusted runtime/configuration (never generated by LLM).
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    agent_id: str = Field(
        ...,
        min_length=3,
        max_length=64,
        pattern=r"^[a-zA-Z0-9_-]+$",
        description="Unique identifier for the agent instance (e.g. 'sre-agent-primary')",
    )
    agent_type: Literal["ai_agent", "system", "human_operator", "automation"] = Field(
        default="ai_agent",
        description="Logical classification of the agent identity",
    )
    version: str = Field(
        ...,
        pattern=r"^\d+\.\d+\.\d+.*$",
        description="Semantic version of the running agent codebase (e.g. '0.4.1')",
    )
    description: Optional[str] = Field(
        default=None,
        max_length=256,
        description="Optional human-readable description of the agent role",
    )
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 UTC creation timestamp",
    )

    @field_validator("agent_id", "version", "description")
    @classmethod
    def validate_no_secrets(cls, value: Optional[str]) -> Optional[str]:
        if value is None:
            return None
        trimmed = value.strip()
        if not trimmed:
            raise ValueError("Field cannot be empty or whitespace only")
        for pattern in SECRET_PATTERNS:
            if pattern.search(trimmed):
                raise ValueError("AgentIdentity fields must not contain tokens, keys, or credentials")
        return trimmed
